routes/web.php
Route::get('/users/datatable','UserController@datatable')->name('users.datatable');
Route::get('/users/editProfile/{id}','UserController@editProfile')->name('users.editProfile');
Route::resource('/users','UserController');

Auth::routes();
////////////////////// login customize ============================

Route::post('/login/user','Auth\LoginController@loginUser')->name('login.user');

//////////////// mark all notifications as read /////////////////////////////
Route::get('markAsRead',function(){
    auth()->user()->unreadNotifications->markAsRead();
    return redirect()->back();
})->name('markAllRead');

////////////////////// mark signle notification as read /////////////////////
Route::get('markRead/{id}',function($id){
    $userUnreadNotification = auth()->user()->unreadNotifications->where('id', $id)->first();
    if($userUnreadNotification) {
        $userUnreadNotification->markAsRead();
    }
    return redirect()->back();
})->name('markReadSingle');

//////////////////////// VIEW ALL NOTIFICATIONS /////////////////////////////////
Route::get('/notifications', function () {
    return view('notifications');
})->name('viewAllNotifications');


/////////////////////// biller request update ////////////////////////
Route::get('/billerUpdateRequest/status/{id}','BillerUpdateRequestController@status')->name('billerUpdateRequest.status');
Route::get('/billerUpdateRequest/datatable','BillerUpdateRequestController@datatable')->name('billerUpdateRequest.datatable');
Route::resource('/billerUpdateRequest','BillerUpdateRequestController');


/////////////////////// customer request update ////////////////////////
Route::get('/customerUpdateRequest/status/{id}','CustomerUpdateRequestController@status')->name('customerUpdateRequest.status');
Route::get('/customerUpdateRequest/datatable','CustomerUpdateRequestController@datatable')->name('customerUpdateRequest.datatable');
Route::resource('/customerUpdateRequest','CustomerUpdateRequestController');

/////////////////////// saleperson request update ////////////////////////
Route::get('/salepersonUpdateRequest/status/{id}','SalePersonUpdateRequestController@status')->name('salepersonUpdateRequest.status');
Route::get('/salepersonUpdateRequest/datatable','SalePersonUpdateRequestController@datatable')->name('salepersonUpdateRequest.datatable');
Route::resource('/salepersonUpdateRequest','SalePersonUpdateRequestController');

/////////////////////// supplier request update ////////////////////////
Route::get('/supplierUpdateRequest/status/{id}','SupplierUpdateRequestController@status')->name('supplierUpdateRequest.status');
Route::get('/supplierUpdateRequest/datatable','SupplierUpdateRequestController@datatable')->name('supplierUpdateRequest.datatable');
Route::resource('/supplierUpdateRequest','SupplierUpdateRequestController');


/////////////////////// product request update ////////////////////////
Route::get('/productUpdateRequest/status/{id}','ProductUpdateRequestController@status')->name('productUpdateRequest.status');
Route::get('/productUpdateRequest/datatable','ProductUpdateRequestController@datatable')->name('productUpdateRequest.datatable');
Route::resource('/productUpdateRequest','ProductUpdateRequestController');

//////////////////////// variants controller ///////////////////////////
Route::resource('/variants','VariantsController');


///////////////////////// area controller//////////////////////////
Route::get('/area/datatable','AreaController@datatable')->name('area.datatable');
Route::resource('/area','AreaController');




/////////////////////// reports //////////////////////
Route::get('/customerReport','ReportsController@customerReport')->name('report.customerReport');
Route::get('/customerReport/{id}','ReportsController@customerReportDetail')->name('report.customerReportDetail');
Route::get('/supplierReport','ReportsController@supplierReport')->name('report.supplierReport');
Route::get('/supplierReport/{id}','ReportsController@supplierReportDetail')->name('report.supplierReportDetail');
Route::get('/brandsReport','ReportsController@brandsReport')->name('report.brandsReport');
Route::get('/categoryReport','ReportsController@categoryReport')->name('report.categoryReport');
Route::get('/bestSellerReport','ReportsController@bestSellerReport')->name('report.bestSellerReport');
Route::get('/warehouseReport','ReportsController@warehouseReport')->name('report.warehouseReport');

Route::get('/productProfitReport','ReportsController@productProfitReport')->name('report.productProfitReport');
Route::get('/salepersonReport','ReportsController@salepersonReport')->name('report.salepersonReport');

/////////////////////// ExpenseVoucherController ///////////////////////
Route::get('/expenseVoucher/datatable','ExpenseVoucherController@datatable')->name('expenseVoucher.datatable');
Route::get('/expenseVoucher/account/{id}','ExpenseVoucherController@accounts')->name('expenseVoucher.account');

Route::get('/expenseVoucher/pdf/{id}','ExpenseVoucherController@pdf')->name('expenseVoucher.pdf');

Route::post('/expenseVoucher/status','ExpenseVoucherController@status')->name('expenseVoucher.status');
Route::post('/expenseVoucher/rcv','ExpenseVoucherController@rcv')->name('expenseVoucher.rcv');
Route::resource('/expenseVoucher','ExpenseVoucherController');

use Automattic\WooCommerce\Client;

Route::get('/woocommerce-testing', function () {
    $woocommerce = new Client(
        'http://plc.dreamevents.pk/', // Your store URL
        'ck_071144b0bededc3065fa6a2ab802812f9420215a', // Your consumer key
        'cs_640f8b68acc60c03891adaa1c6f52f1513b4716a', // Your consumer secret
        [
            'wp_api' => true, // Enable the WP REST API integration
            'version' => 'wc/v3' // WooCommerce WP REST API version
        ]
    );
    // storage/
    $filename         = storage_path('BRANDS/FINDER.csv');
    // dd($filename);
    $delimiter        = ',';

    if (!file_exists($filename) || !is_readable($filename))
        return false;

    $header = null;
    $data = [];
    if (($handle = fopen($filename, 'r')) !== false)
    {
        while (($row = fgetcsv($handle, 1000, $delimiter)) !== false)
        {
            if (!$header)
                  $header = $row;
            else
                {
                  if(count($row) == count($header))
                  {

                    $data[] = array_combine($header, $row);
                  }
                  else {
                    dd($row);
                  }
                }

        }
        fclose($handle);
    }
    for ($i = 0; $i < count($data); $i ++)
    {
        // dd($data[$i]);
        $product = [
            'name' => $data[$i]['Product Name'],
            'regular_price' => $data[$i]['price'],
            'description' => $data[$i]['Description'],
            'short_description' => $data[$i]['Description'],
            'categories' => [
                ['id' => 145]
            ],
            'images' => [
                [
                    'src' => $data[$i]['Image']
                ]
            ]
        ];
        $woo = $woocommerce->post('products', $product);
    }
    dd("done");
});

// //uploading products
// use App\AccountDetails;
// use App\Products;
// use App\Brands;
// use App\Category;
// use App\Unit;
// use App\Subcategory;
// use App\HeadCategory;
// use App\Vendors;
// use App\ProductSupplier;
// Route::get('/add/data',function(){
// //     // dd(storage_path());
//     $filename         = storage_path().'/app/product structure list.csv';
//     $delimiter        = ',';
//     if (!file_exists($filename) || !is_readable($filename))
//         return false;
//     $header = null;
//     $data = array();
//     if (($handle = fopen($filename, 'r')) !== false)
//     {
//         while (($row = fgetcsv($handle, 1000, $delimiter)) !== false)
//         {
//             if (!$header)
//                 $header = $row;
//             else
//                 {
//                     $data[] = array_combine($header, $row);
//                 }

//         }
//         fclose($handle);
//     }
//     // $account = AccountDetails::latest('created_at')->orderBy('Code','desc')->where('c_id',6)->first();
//     // dd($account);
//     // if($account == null)
//     // {
//         $id = 001;
//         // dd($id);
//     // }
//     // else
//     // {
//     //     $id = substr($account->Code, strpos($account->Code, '-',strpos($account->Code, '-')+1)+1) +1;
//     // }

    // dd($data);
    // for ($i = 0; $i < count($data); $i ++)
    // {
//         // if($data[$i]['vstatus'] == 0)
//         // {
//             $sub = Subcategory::where('s_cat_name',$data[$i]['sub-category'])->first();
//             $cat = Category::where('cat_name',$data[$i]['category'])->first();
//             $brand = Brands::where('b_name',$data[$i]['brand'])->first();
//             $unit= Unit::where('u_name',$data[$i]['unit'])->first();
//             $vendor = Vendors::where('v_type','Supplier')->where('name',$data[$i]['Supplier'])
//             ->where('company',$data[$i]['Company'])->first();
//             // if($vendor == null)
//             // {
//             //     $vendor = Vendors::create([
//             //         'v_type' => 'Supplier',
//             //         'name' => $data[$i]['Supplier'],
//             //         'company' => $data[$i]['Company'],
//             //     ]);
//             //     $hcat = HeadCategory::where('name','Payables')->first();
//             //     $str_length = strlen((string)$id)+2;
//             //     $id = substr("0000{$id}", -$str_length);
//             //     $code = $hcat->code.'-'.$id;
//             //     $data1 = [
//             //         'Code' => $code,
//             //         'name_of_account' => $data[$i]['Supplier'].' - '.$data[$i]['Company'],
//             //         'c_id' => $hcat->id,
//             //     ];
//             //     AccountDetails::create($data1);
//             //     $id++;
//             // }

app/Area.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Area extends Model
{
    protected $table = 'area';
    protected $primaryKey = 'id';
    protected $fillable = [
        'name',
    ];

    public function customer()
    {
        return $this->hasOne('App\Vendors','a_id','id');
    }
    public function customerreq()
    {
        return $this->hasOne('App\VendorsUpdateRequest','a_id','id');
    }
}

app/Http/Controllers/AreaController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Area;
use App\User;
use DataTables;
use Auth;
use DB;
use App\Notifications\AddNotification;
use Illuminate\Support\Facades\Notification;

class AreaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index(Request $request)
    {
        $menu_id            =   getMenuId($request);
        $permissions        =   getRolePermission($menu_id);
        return view('area.index',compact('permissions'));
    }

    public function datatable()
    {
        $area=Area::withCount(['customer as total' => function($query) {
            $avg = $query->where('v_type','Customer')->select(DB::raw('count(id)'));
        }])
        ->get();
        return DataTables::of($area)->make();
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data=[
            'isEdit' => false
        ];
        return view('area.create',$data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = $request->validate([
            'name'      =>  'required|string|max:255|unique:area'
        ]);
        $u_id = Auth::user()->id;
        $role_id = Auth::user()->r_id;
        $env_a_id = config('app.adminId');
        $env_m_id = config('app.managerId');
        $u_name = Auth::user()->name;
        $user = User::where('r_id',config('app.adminId'))->get();
        $data1 = [
            'notification' => 'New arae has been added by '.$u_name,
            'link' => url('').'/area',
            'name' => 'View Areas',
        ];
        Notification::send($user, new AddNotification($data1));
        Area::create($data);
        toastr()->success('Area added successfully!');
        return redirect()->back();
    }
    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Area $area)
    {
        $data=[
            'isEdit' => true,
            'area' =>$area
        ];
        return view('area.create',$data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request,Area $area)
    {
        $data = $request->validate([
            'name'      =>  'required|string|max:255|unique:area,name,'.$area->id
        ]);
        $area->update($data);
        toastr()->success('Area Updated successfully!');
        return redirect(url('').'/area');
    }
}

resources/views/area/create.blade.php
@extends('layouts.master')
@section('top-styles')
@toastr_css
@section('sidebar-name1')
<li>
    <a href="{{url('')}}/area">Areas</a>
    <i class="fa fa-circle"></i>
</li>
<li>
    <span>{{$isEdit ? 'Edit' : 'Add'}} Area</span>
</li>
@endsection
@section('content')
    <div class="row">
        <div class="col-md-12">
            <!-- BEGIN VALIDATION STATES-->
            <div class="portlet light portlet-fit portlet-form bordered" id="form_wizard_1">
                <div class="portlet-title">
                    <div class="caption">
                        <i class=" fa fa-area-chart font-green"></i>
                        <span class="caption-subject font-green sbold uppercase">{{$isEdit ? 'Edit' : 'Add'}} Area</span>
                    </div>

                </div>
                <div class="portlet-body">
                    <!-- BEGIN FORM-->
                    <form action="{{$isEdit ? route('area.update',$area->id) :  route('area.store')}} " class="form-horizontal" method="POST" >
                        @csrf
                        @if ($isEdit)
                            @method('PUT')
                        @endif
                        <div class="form-body">

                            <div class="row">
                                <div class="col-sm-6">
                                    <div class="form-outline">
                                        <label >Area Name*</label>
                                        <input value="{{$area->name ?? old('name')}}" class="form-control" type="text" placeholder="Enter Area Name" name="name" >
                                        <span class="text-danger">{{$errors->first('name') ? 'Already Exist or Enter Name' : null}}</span>
                                    </div>
                                </div>
                            </div>

                        <div class="form-actions">
                            <div class="row">
                                <div class="col-md-offset-0 ">
                                    <button type="submit" class="btn green">Submit</button>
                                </div>
                            </div>
                        </div>
                    </form>
                    <!-- END FORM-->
                </div>
            </div>
            <!-- END VALIDATION STATES-->
        </div>
    </div>

@endsection
@section('custom-script')
@toastr_js
@toastr_render
@endsection

resources/views/area/index.blade.php
@extends('layouts.master')
@section('top-styles')
<style>
    .tableview
    {
        background-color:#F0F0F0;
        padding: 20px;
        border-radius: 5px;
        border:1px solid  #e7ecf1;
    }
</style>
<style>
    #GFG {
        text-decoration: none;
    }
    thead {
	    background-color: #ADD8E6;
    }
    .modal-header{
        background: #32c5d2 !important;
    }
</style>
@toastr_css
<!-- DataTables -->
<link rel="stylesheet" href="{{url('')}}/assets/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css">
<link rel="stylesheet" href="{{url('')}}/assets/plugins/datatables-responsive/css/responsive.bootstrap4.min.css">

@section('sidebar-name1')
<li>
    <a href="{{url('')}}/area">Areas</a>
</li>
@endsection
@section('content')
    <div class="row">
        <div class="col-md-12">
            <!-- Begin: life time stats -->
            <div class="portlet light portlet-fit portlet-datatable bordered">
                <div class="portlet-title">

                </div>
                <div class="portlet-body">
                    <div class="tabbable-line">
                        <div class="row">
                            <div class="col-md-12 col-sm-12">
                                <div class="portlet grey-cascade box">
                                    <div class="portlet-title" style="background: #32c5d2;">
                                        <div class="caption col-md-12 col-sm-12 col-xs-12 row">
                                            <div class="col-md-4  col-sm-4 col-xs-5">
                                                <i class="fa fa-area-chart font-white"></i>View Areas
                                            </div>
                                            <div class="col-md-5 col-sm-3"></div>
                                            <div class="col-md-3 col-sm-5 col-xs-7">

                                                @if(in_array('Add',$permissions))
                                                    <a id="GFG" href="{{route('area.create')}}" >
                                                        <button style="background: #00CCFF; margin-left:20px; margin-top:0px" type="button"  class="btn btn-block btn-primary btn-md ">Add Area</button>
                                                    </a>
                                                @endif
                                            </div>
                                        </div>
                                    </div>
                                    <div class="portlet-body">
                                        <div class="custom_datatable">
                                            <form action="#" id="advanceSearch">
                                                <div class="tableview">
                                                <div class="row">
                                                    <div class="col-md-8">
                                                    <div class="form-group">
                                                        <label for="">Area Name</label>
                                                        <input type="text" name="name" id="autocomplete-ajax1" class="form-control" placeholder="Area Name" style=" z-index: 2;" autocomplete="off">
                                                    </div>
                                                    </div>

                                                    <div class="col-md-4"></div>
                                                    <div class="col-md-4">
                                                    <div class="form-group">
                                                        {{-- <label for="">Unit Name</label> --}}
                                                        <label for="" style="visibility: hidden">.</label>
                                                        <button id="search" style="background: #32c5d2" class="btn btn-light-theme btn-block waves-effect waves-light">
                                                        <i class="fa fa-search pr-1"></i> Search</button>
                                                    </div>
                                                    </div>
                                                </div>
                                                </div>
                                            </form>
                                            <div class="table-responsive">
                                            <table id="example" class="table table-striped table-bordered" style="width:100%">
                                                    <thead>
                                                        <tr>
                                                            <th width="7%">S.No</th>
                                                            <th>Name</th>
                                                            <th>Total Customers</th>
                                                            <th width="15%">Action</th>
                                                        </tr>
                                                    </thead>
                                                    <tbody>
                                                    </tbody>

                                                </table>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>




                    </div>
                </div>
            </div>
        </div>
        <!-- End: life time stats -->
    </div>

@section('custom-script')
@toastr_js
@toastr_render

    <script type="text/javascript">
        $(document).ready(function () {
            var table = $('#example').DataTable({
                processing: true,
                order: [[ 0, "desc" ]],
                serverSide: true,
                ajax: '{{route("area.datatable")}}',
                "columns": [{
                        "data": "id",
                        "defaultContent": ""
                    },
                    {
                        "data": "name",
                        "defaultContent": ""
                    },
                    {
                        "data": "total",
                        "defaultContent": ""
                    },
                    {
                        "data": "id",
                        "defaultContent": ""
                    },
                ],
                "columnDefs": [{
                        "targets": 'no-sort',
                        "orderable": false,
                    },
                    {
                        "targets": 0,
                        "render": function (data, type, row, meta) {
                            return meta.row + 1;
                        },
                    },
                    {
                        "targets": -1,
                        "render": function (data, type, row, meta) {
                            var edit = '{{route("area.edit",[":id"])}}';
                            edit = edit.replace(':id', row.id );
                            return `
                            @if(in_array('edit',$permissions))
                                <a id="GFG" href="` + edit + `" class="text-info p-1">
                                    <button type="button" class="btn blue edit" >
                                        <i class="fa fa-edit"></i>
                                    </button>
                                </a>
                            @endif
                            `;
                        },
                    },
                ],
            });
            $('#advanceSearch').submit(function(e){
                e.preventDefault();
                // var date = moment($('input[name="created_at"]').val(),'YYYY/MM/DD').format('YYYY-MM-DD');
                // if(date === 'Invalid date')
                // {
                // date = '';
                // }
                // console.log($('.ver-status').val());
                table.columns(1).search($('input[name="name"]').val());
                table.draw();
            });
        });

    </script>
@endsection
@endsection