routes/web.php
Route::get('/reports/saleCostingsearch/{Y}/pdf/year','HomeController@saleCostingSearchYPDF')->name('reports.saleCostingsearchYpdf');//pdf for year
Route::get('/reports/saleCostingsearch/{D}/excel/date','HomeController@saleCostingSearchDExcel')->name('reports.saleCostingsearchDExcel');//excel for one date
Route::get('/reports/saleCostingsearch/{D}/pdf/date','HomeController@saleCostingSearchDPDF')->name('reports.saleCostingsearchDpdf');//pdf for one date
Route::get('/reports/saleCostingsearch/{from}/{to}/excel/date','HomeController@saleCostingSearchDatesExcel')->name('reports.saleCostingsearchDatesExcel');//excel for date diff


//////////////// product controller /////////////////////////

Route::get('/product/datatable','ProductController@datatable')->name('product.datatable');
Route::get('/product/modal/{id}','ProductController@modal')->name('product.modal');
Route::get('/product/variants/{id}','ProductController@variants')->name('product.variants');
Route::get('/product/Pvariants/{id}','ProductController@Pvariants')->name('product.Pvariants');
Route::get('/product/Pvariantsforfinishproduct/{id}','ProductController@Pvariantsforfinishproduct')->name('product.Pvariantsforfinishproduct');
Route::get('/product/sales/{id}','ProductController@sales')->name('product.sales');
Route::get('/product/salesProduct/{id}','ProductController@salesProduct')->name('product.salesProduct');
Route::get('/product/detail/{id}','ProductController@detail')->name('product.detail');
Route::get('/product/excel','ProductController@excel')->name('product.excel');
Route::get('/product/finishProducts','ProductController@finishProducts')->name('product.finishProducts');
Route::get('/product/finishProducts/datatable','ProductController@finishProductsDatatable')->name('product.finishProducts.datatable');
Route::get('/product/finishProducts/edit/{id}','ProductController@finishProductEdit')->name('product.finishProducts.edit');
Route::put('/product/finishProducts/update/{id}','ProductController@finishProductUpdate')->name('product.finishProducts.update');
Route::get('/product/finish/excel','ProductController@Finishexcel')->name('product.finish.excel');
Route::get('/product/add','ProductController@add')->name('product.add');
Route::get('/product/stockShow/{id}','ProductController@stockShow')->name('product.stockShow');
Route::get('/product/add/show/{id}','ProductController@addSingleProduct')->name('product.add.show');
Route::get('/product/add/datatable','ProductController@addDT')->name('product.add.datatable');

Route::get('/product/productsearch/{id}','ProductController@productsearch')->name('product.productsearch');
Route::post('/product/addFinishProduct','ProductController@addFinishProduct')->name('product.addFinishProduct');
Route::resource('/product','ProductController');
Route::post('/product/status','ProductController@status')->name('product.status');
Route::post('/product/variants/status','ProductController@Vstatus')->name('product.variants.status');

/////////////////////// brands controller //////////////////////////

Route::get('/brands/datatable','BrandsController@datatable')->name('brands.datatable');
Route::get('/brands/excel','BrandsController@excel')->name('brands.excel');
Route::resource('/brands','BrandsController');
Route::post('/brands/status','BrandsController@status')->name('brands.status');

//////////////////////// unit controller ///////////////////////////

Route::get('/unit/datatable','UnitController@unitDatatable')->name('unit.datatable');
Route::resource('/unit','UnitController');
Route::post('/unit/status','UnitController@status')->name('unit.status');

///////////////////// category controller //////////////////////

Route::get('/category/datatable','CategoryController@datatable')->name('category.datatable');
Route::get('/category/excel','CategoryController@excel')->name('category.excel');
Route::resource('/category','CategoryController');
Route::post('/category/status','CategoryController@status')->name('category.status');

//////////////////// sub category controller ///////////////////////

Route::get('/subcategory/datatable','SubcategoryController@datatable')->name('subcategory.datatable');
Route::resource('/subcategory','SubcategoryController');
Route::post('/subcategory/status','SubcategoryController@status')->name('subcategory.status');

////////////// city controller ///////////////////////

Route::post('/city/status','CityController@status')->name('city.status');
Route::get('/city/datatable','CityController@datatable')->name('city.datatable');
Route::resource('/city','CityController');

//////////////////// warehouse controller /////////////////////

Route::get('/warehouse/datatable','WarehouseController@datatable')->name('warehouse.datatable');
Route::resource('/warehouse','WarehouseController');

/////////////////// product transfer controller /////////////////////////

Route::post('/productTransfer/status','ProductTransaferHistoryController@status')->name('productTransfer.status');
Route::get('/productTransfer/product','ProductTransaferHistoryController@product')->name('productTransfer.product');
Route::get('/productTransfer/excel','ProductTransaferHistoryController@excel')->name('productTransfer.excel');
Route::get('/productTransfer/pdf','ProductTransaferHistoryController@pdf')->name('productTransfer.pdf');
Route::post('/productTransfer/search','ProductTransaferHistoryController@search')->name('productTransfer.search');
Route::get('/productTransfer/search/{M}/{pname}/type/{fw}/{tw}/excel/month','ProductTransaferHistoryController@searchMExcel')->name('productTransfer.searchMExcel');//excel for month
Route::get('/productTransfer/search/{Y}/{pname}/type/{fw}/{tw}/excel/year','ProductTransaferHistoryController@searchYExcel')->name('productTransfer.searchYExcel');//excel for year
Route::get('/productTransfer/search/{D}/{pname}/type/{fw}/{tw}/excel/date','ProductTransaferHistoryController@searchDExcel')->name('productTransfer.searchDExcel');//excel for one date
Route::get('/productTransfer/search/{from}/{to}/{pname}/type/{fw}/{tw}/excel/date','ProductTransaferHistoryController@searchDatesExcel')->name('productTransfer.searchDatesExcel');//excel for date diff
Route::resource('/productTransfer','ProductTransaferHistoryController');

///////////////// company controller ////////////////////////

Route::get('/company/datatable','CompanyController@datatable')->name('company.datatable');
Route::get('/company/excel','CompanyController@excel')->name('company.excel');
Route::get('/company/pdf','CompanyController@pdf')->name('company.pdf');
Route::resource('/company','CompanyController');

/////////////////// group controller //////////////////////////

Route::get('/group/datatable','GroupController@datatable')->name('group.datatable');
Route::resource('/group','GroupController');

///////////////counter controller///////////////////////////
Route::get('/counter/datatable','CounterController@datatable')->name('counter.datatable');
Route::resource('/counter','CounterController');


///////////////CounterAssignedController ///////////////////////////
Route::get('/assigned/datatable','CounterAssignedController@datatable')->name('assigned.datatable');
Route::resource('/assigned','CounterAssignedController');

/////////////// customer controller ///////////////////////

Route::post('/customer/status','CustomerController@status')->name('customer.status');
Route::get('/customer/datatable','CustomerController@datatable')->name('customer.datatable');
Route::get('/customer/excel','CustomerController@excel')->name('customer.excel');
Route::get('/customer/pdf','CustomerController@pdf')->name('customer.pdf');
Route::get('/customer/balance/{id}','CustomerController@balance')->name('customer.balance');
Route::resource('/customer','CustomerController');

///////////////// supplier controller /////////////////

Route::post('/supplier/status','SupplierController@status')->name('supplier.status');
Route::get('/supplier/datatable','SupplierController@datatable')->name('supplier.datatable');
Route::get('/supplier/excel','SupplierController@excel')->name('supplier.excel');
Route::get('/supplier/pdf','SupplierController@pdf')->name('supplier.pdf');
Route::get('/supplier/products/{id}','SupplierController@Products')->name('supplier.products');
Route::resource('/supplier','SupplierController');

////////////////// sale person controller ////////////////////////////////

Route::post('/saleperson/status','SalePersonController@status')->name('saleperson.status');
Route::get('/saleperson/datatable','SalePersonController@datatable')->name('saleperson.datatable');
Route::get('/saleperson/excel','SalePersonController@excel')->name('saleperson.excel');
Route::get('/saleperson/pdf','SalePersonController@pdf')->name('saleperson.pdf');
Route::resource('/saleperson','SalePersonController');

//////////////////// purchase controller  ///////////////////////////

Route::post('/purchase/search','PurchaseOrderController@search')->name('purchase.search');
Route::get('/purchaseDetail/{id}','PurchaseOrderController@purchaseDetail')->name('purchaseDetail');
Route::get('/purchase/pdf/{id}','PurchaseOrderController@pdf')->name('purchase.pdf');
Route::get('/purchase/pdf','PurchaseOrderController@pdf1');
Route::get('/purchase/grr/{no,id}','PurchaseOrderController@GRR')->name('purchase.GRR');
Route::get('/purchase/grr1/{no}','PurchaseOrderController@GRR1');
Route::get('/purchase/document/{id}','PurchaseOrderController@document')->name('purchase.document');
Route::get('/purchase/invoice/{id}','PurchaseOrderController@invoice')->name('purchase.invoice');
Route::get('/purchase/product/{id}','PurchaseOrderController@product')->name('purchase.product');
Route::get('/purchase/grn/{id}','PurchaseOrderController@GRN')->name('purchase.grn');
Route::get('/purchase/report','PurchaseOrderController@report')->name('purchase.report');
// Route::get('/purchase/excel','PurchaseOrderController@excel')->name('purchase.excel');
Route::resource('/purchase','PurchaseOrderController');

app/Unit.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Unit extends Model
{
    protected $table = 'units';
    protected $primaryKey = 'id';
    protected $fillable = [
        'u_name',
        'created_by',
        'updated_by',
        'status'
    ];

    public function products()
    {
        return $this->belongsTo('App\Products');
    }

    public function createUser()
    {
        return $this->hasOne('App\User','id','created_by');
    }

    public function updateUser()
    {
        return $this->hasOne('App\User','id','updated_by');
    }
}

app/Http/Controllers/UnitController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Unit;
use DataTables;
use Auth;

class UnitController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index(Request $request)
    {
        $menu_id            =   getMenuId($request);
        $permissions        =   getRolePermission($menu_id);
        return view('unit.index',compact('permissions'));
    }

    public function unitDatatable()
    {
        $unit=Unit::all();
        return DataTables::of($unit)->make();
    }

    public function status(Request $request)
    {
        // dd($request->all());
        $response['status'] = false;
        $response['message'] = 'Oops! Something went wrong.';
        $u_id = Auth::user()->id;
        $id     = $request->input('id');
        $status = $request->input('status');

        $item = Unit::find($id);
        if ($item->update(['status' => $status])) {
            $item->update([
                'status' => $status,
                'updated_by' => $u_id
            ]);
            $response['status'] = $status;
            $response['message'] = 'status updated successfully.';
            return response()->json($response, 200);
        }
        return response()->json($response, 409);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data=[
            'isEdit' =>false
        ];
        return view('unit.create',$data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = $request->validate([
            'u_name'      =>  'required|string|max:255|unique:units'
        ]);
        $data['created_by'] = Auth::user()->id;
        $unit = Unit::create($data);
        if(isset($request->request_type) && $request->request_type == "ajax")
        {
            $response['message'] = 'Unit added successfully!';
            $response['unit'] = $unit;
            return response()->json($response, 200);
        }
        toastr()->success('Unit added successfully!');
        return redirect()->back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Unit $unit)
    {
        if(request()->ajax())
        {
            return $unit;
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Unit $unit)
    {
        $data=[
            'isEdit' => true,
            'unit' =>$unit
        ];
        return view('unit.create',$data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request,Unit $unit)
    {
        $data = $request->validate([
            'u_name'      =>  'required|string|max:255|unique:units,u_name,'.$unit->id
        ]);
        $data['updated_by'] = Auth::user()->id;
        $unit->update($data);
        toastr()->success('Unit updated successfully!');
        return redirect(url('').'/unit');
    }
}

resources/views/unit/create.blade.php
@extends('layouts.master')
@section('top-styles')
@toastr_css
@section('sidebar-name1')
<li>
    <a href="{{url('')}}/unit">Unit</a>
    <i class="fa fa-circle"></i>
</li>
<li>
    <span>{{$isEdit ? 'Edit' : 'Add'}} Unit</span>
</li>
@endsection
@section('content')
    <div class="row">
        <div class="col-md-12">
            <!-- BEGIN VALIDATION STATES-->
            <div class="portlet light portlet-fit portlet-form bordered" id="form_wizard_1">
                <div class="portlet-title">
                    <div class="caption">
                        <i class=" fa fa-balance-scale font-green"></i>
                        <span class="caption-subject font-green sbold uppercase">{{$isEdit ? 'Edit' : 'Add'}} Unit</span>
                    </div>

                </div>
                <div class="portlet-body">
                    <!-- BEGIN FORM-->
                    <form action="{{$isEdit ? route('unit.update',$unit->id) :  route('unit.store')}} " class="form-horizontal" method="POST" >
                        @csrf
                        @if ($isEdit)
                            @method('PUT')
                        @endif
                        <div class="form-body">

                            <div class="row">
                                <div class="col-sm-6">
                                    <div class="form-outline">
                                        <label >Unit Name*</label>
                                        <input value="{{$unit->u_name ?? old('u_name')}}" class="form-control" type="text" placeholder="Enter Unit Name" name="u_name" >
                                        <span class="text-danger">{{$errors->first('u_name') ? 'Unit already exist or Enter unit' : null}}</span>
                                    </div>
                                </div>
                            </div>

                        <div class="form-actions">
                            <div class="row">
                                <div class="col-md-offset-0">
                                    <button type="submit" class="btn green">Submit</button>
                                </div>
                            </div>
                        </div>
                    </form>
                    <!-- END FORM-->
                </div>
            </div>
            <!-- END VALIDATION STATES-->
        </div>
    </div>

@endsection
@section('custom-script')
@toastr_js
@toastr_render
@endsection

resources/views/unit/index.blade.php
@extends('layouts.master')
@section('top-styles')
<style>
    .tableview
    {
        background-color:#F0F0F0;
        padding: 20px;
        border-radius: 5px;
        border:1px solid  #e7ecf1;
    }
</style>
<style>
    #GFG {
        text-decoration: none;
    }
    thead {
	    background-color: #ADD8E6;
    }
    .modal-header{
        background: #32c5d2 !important;
    }
</style>
@toastr_css
<!-- DataTables -->
<link rel="stylesheet" href="{{url('')}}/assets/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css">
<link rel="stylesheet" href="{{url('')}}/assets/plugins/datatables-responsive/css/responsive.bootstrap4.min.css">

@section('sidebar-name1')
<li>
    <a href="{{url('')}}/unit">Unit</a>
</li>
@endsection
@section('content')
    <div class="row">
        <div class="col-md-12">
            <!-- Begin: life time stats -->
            <div class="portlet light portlet-fit portlet-datatable bordered">
                <div class="portlet-title">

                </div>
                <div class="portlet-body">
                    <div class="tabbable-line">
                        <div class="row">
                            <div class="col-md-12 col-sm-12">
                                <div class="portlet grey-cascade box">
                                    <div class="portlet-title" style="background: #32c5d2;">
                                        <div class="caption" style="width: -webkit-fill-available; ">
                                            <i class="fa fa-balance-scale font-white"></i>View Units
                                            @if(in_array('Add',$permissions))
                                                <a id="GFG" href="{{route('unit.create')}}" class="col-md-2" style="float: right">
                                                    <button  style="background: #00CCFF" type="button"  class="btn btn-block btn-info btn-md ">Add Unit</button>
                                                </a>
                                            @endif
                                        </div>
                                    </div>

                                    <div class="portlet-body">
                                        <div class="custom_datatable">
                                            <form action="#" id="advanceSearch">
                                                <div class="tableview">
                                                <div class="row">
                                                    <div class="col-md-4">
                                                    <div class="form-group">
                                                        <label for="">Unit Name</label>
                                                        <input type="text" name="u_name" id="autocomplete-ajax1" class="form-control" placeholder="Unit Name" style=" z-index: 2;" autocomplete="off">
                                                    </div>
                                                    </div>
                                                    <div class="col-md-4">
                                                    <div class="form-group">
                                                        <label for="">Active Status</label>
                                                        <select name="status" class="form-control selectpicker">
                                                        <option selected="" value="">No Filter</option>
                                                        <option value="1">Active</option>
                                                        <option value="0">InActive</option>
                                                        </select>
                                                    </div>
                                                    </div>
                                                    <div class="col-md-4"></div>
                                                    <div class="col-md-4">
                                                    <div class="form-group">
                                                        {{-- <label for="">Unit Name</label> --}}
                                                        <label for="" style="visibility: hidden">.</label>
                                                        <button id="search" style="background: #32c5d2" class="btn btn-light-theme btn-block waves-effect waves-light">
                                                        <i class="fa fa-search pr-1"></i> Search</button>
                                                    </div>
                                                    </div>
                                                </div>
                                                </div>
                                            </form>
                                            <div class="table-responsive">
                                            <table id="example" class="table table-striped table-bordered" style="width:100%">
                                                    <thead>
                                                        <tr>
                                                            <th width="7%">S.No</th>
                                                            <th>Name</th>
                                                            <th width="15%">Action</th>
                                                        </tr>
                                                    </thead>
                                                    <tbody>
                                                    </tbody>

                                                </table>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>




                    </div>
                </div>
            </div>
        </div>
        <!-- End: life time stats -->
    </div>
    @section('modal')
        <div id="myModal" class="modal fade" role="dialog">
            <div class="modal-dialog">

                <!-- Modal content-->
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">×</button>
                        <h4 class="modal-title">Unit</h4>
                    </div>
                    <div class="modal-body">

                        <div class="row">
                            <div class="col-sm-6">
                                <div class="form-outline">
                                    <label >Unit Name</label>
                                    <input class="form-control" type="text" placeholder="Enter Unit Name" id="u_name" readonly>
                                </div>
                            </div>
                        </div>

                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    </div>
                </div>

            </div>
        </div>
    <!--End Modal-->
    @endsection
    @section('custom-script')
    @toastr_js
    @toastr_render
        {{-- view one product --}}
        <script>
            $(document).on('click','.view',function(){
                var id=$(this).attr("id");
                $.ajax({
                    url:"{{url('')}}/unit/"+id,
                    method:"GET",
                    error: function (request, error) {
                                alert(" Can't do because: " + error +request);
                            },
                    success:function(data){
                        console.log(data);
                        $('#u_name').val(data.u_name);
                    }
                });
            });
        </script>
        <script type="text/javascript">
            $(document).ready(function () {
                var table = $('#example').DataTable({
                    processing: true,
                    serverSide: true,
                    order: [[ 0, "desc" ]],
                    scrollX: true,
                    ajax: '{{route("unit.datatable")}}',
                    "columns": [{
                            "data": "id",
                            "defaultContent": ""
                        },
                        {
                            "data": "u_name",
                            "defaultContent": ""
                        },
                        {
                            "data": "status",
                            "defaultContent": ""
                        },
                    ],
                    "columnDefs": [{
                            "targets": 'no-sort',
                            "orderable": false,
                        },
                        {
                            "targets": 0,
                            "render": function (data, type, row, meta) {
                                return meta.row + 1 ;
                            },
                        },
                        {
                            "targets": -1,
                            "render": function (data, type, row, meta) {
                                var edit = '{{route("unit.edit",[":id"])}}';
                                edit = edit.replace(':id', row.id);
                                var checked = row.status == 1 ? 'checked' : null;
                                return `
                                @if(in_array('edit',$permissions))
                                    <a id="GFG" href="` + edit + `" class="text-info p-1">
                                        <button type="button" class="btn blue edit" >
                                            <i class="fa fa-edit"></i>
                                        </button>
                                    </a>
                                @endif
                                @if(in_array('show',$permissions))
                                    <button type="button" data-target="#myModal" data-toggle="modal"  class="btn green view" id="`+row.id +`">
                                        <i class="icon-eye"></i>
                                    </button>
                                @endif
                                @if(in_array('status',$permissions))
                                    <input class="status" type="checkbox" data-plugin="switchery" data-color="#005CA3" data-size="small" ` +
                                                checked + ` value="` + row.id + `">
                                @endif
                                `;
                            },
                        },
                    ],
                    "drawCallback": function (settings) {
                        var elems = Array.prototype.slice.call(document.querySelectorAll('.status'));
                        if (elems) {
                        elems.forEach(function (html) {
                            var switchery = new Switchery(html, {
                                color: '#007bff'
                                , secondaryColor: '#dfdfdf'
                                , jackColor: '#fff'
                                , jackSecondaryColor: null
                                , className: 'switchery'
                                , disabled: false
                                , disabledOpacity: 0.5
                                , speed: '0.1s'
                                , size: 'small'
                                });

                            });
                        }
                        $('.status').change(function () {
                            var $this = $(this);
                            var id = $this.val();
                            var status = this.checked;

                            if (status) {
                                status = 1;
                            } else {
                                status = 0;
                            }
                    // console.log(status);
                        axios
                            .post('{{route("unit.status")}}', {
                            _token: '{{csrf_token()}}',
                            _method: 'post',
                            id: id,
                            status: status,
                            })
                            .then(function (responsive) {
                            console.log('responsive');
                            // location.reload();
                            })
                            .catch(function (error) {
                            console.log(error);
                            });
                        });

                    },
                });
                $('#advanceSearch').submit(function(e){
                    e.preventDefault();
                    // var date = moment($('input[name="created_at"]').val(),'YYYY/MM/DD').format('YYYY-MM-DD');
                    // if(date === 'Invalid date')
                    // {
                    // date = '';
                    // }
                    // console.log($('.ver-status').val());
                    table.columns(1).search($('input[name="u_name"]').val());
                    table.columns(2).search($('select[name="status"]').val());
                    table.draw();
                });

            });

        </script>
    @endsection
@endsection